pipeline {
  agent any
  stages {
    stage('Test') {
      steps { sh 'python -m py_compile app.py' }
    }
    stage('Build') {
      steps { sh 'docker build -t sample-api:${BUILD_NUMBER} .' }
    }
  }
}
